language: python
python:
 - 2.7
 - 3.5
 - 3.6
sudo: false
env:
  - DISPLAY=:0.0
install:
  - pip install tox-travis
script:
  - export APPLITOOLS_BATCH_ID=`uuidgen -t`
  - echo $APPLITOOLS_BATCH_ID
  - tox
